import type { Metadata } from 'next';
import '@/globals.css';
import { lusitana } from '@/fonts';
import Sidebar from '@/components/layout/sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${lusitana.className} antialiased`}>
        <div className='h-screen flex flex-row background'>
          <div className='w-64 separatorRight'>
            <Sidebar />
          </div>
          <div className='w-screen'>{children}</div>
        </div>
      </body>
    </html>
  );
}
