import type { Metadata } from 'next';
import '@/globals.css';
import { inter, lusitana } from '@/fonts';
import AppShell from '@/components/layout/appShell';
import Login from '@/login/page';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = true;

  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${lusitana.variable} ${inter.className} antialiased`}
      >
        <div className='h-screen flex flex-row background'>
          {isAuthenticated ? (
            <AppShell>{children}</AppShell>
          ) : (
            <>
              <Login />
            </>
          )}
        </div>
      </body>
    </html>
  );
}
